[package]
name = "day2"
version = "0.1.0"
authors = ["stratosphericvibes <vermatanyax@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
lazy_static = "1.4"
regex = "1"